### ISSUE TITLE
Extra output when running tests

### ISSUE THREAD

**Issue by bencoveney** [bencoveney/ts-react-boilerplate#25]
There is some duplicate output when running tests - is this an indication that something is misconfigured or running twice? Either way it would be helpful to tidy up some of this output.

> karma start

(node:488) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
i ｢wdm｣: wait until bundle finished: noop

**[at-loader] Using typescript@2.8.3 from typescript and "tsconfig.json" from G:\Code\ts-react-boilerplate/tsconfig.json.**

**[at-loader] Checking started in a separate process...**

**[at-loader] Ok, 2.497 sec.**
**i ｢wdm｣: Version: webpack 4.6.0**
**Time: 22917ms**
**Built at: 2018-04-23 22:55:47**
**Entrypoint src/tests.ts = src/tests.ts**
**i ｢wdm｣: Compiled successfully.**
23 04 2018 22:55:48.149:INFO [karma]: Karma v2.0.2 server started at http://0.0.0.0:9876/
23 04 2018 22:55:48.152:INFO [launcher]: Launching browser Chrome with unlimited concurrency
23 04 2018 22:55:48.159:INFO [launcher]: Starting browser Chrome
**i ｢wdm｣: Compiling...**

**[at-loader] Checking started in a separate process...**

**[at-loader] Ok, 0.002 sec.**
**i ｢wdm｣: Version: webpack 4.6.0**
**Time: 12727ms**
**Built at: 2018-04-23 22:55:50**
**Entrypoint src/tests.ts = src/tests.ts**
**i ｢wdm｣: Compiled successfully.**
23 04 2018 22:55:51.526:INFO [Chrome 65.0.3325 (Windows 10 0.0.0)]: Connected on socket ZS_icAnARxo-aRqAAAAA with id 39393682

  <Header />
    √ Should create a header with the correct text

  <App />
    √ Should start counting once it is mounted
    √ Should render initially

Chrome 65.0.3325 (Windows 10 0.0.0): Executed 3 of 3 SUCCESS (0.114 secs / 0 secs)
TOTAL: 3 SUCCESS

**Comment by bencoveney** [comment]
Also seen when tests fail:

23 04 2018 23:02:40.015:INFO [Chrome 65.0.3325 (Windows 10 0.0.0)]: Connected on socket rQApPWk9suanR74oAAAA with id 25839354

  <Header />
    √ Should create a header with the correct text

  <App />
    × Should start counting once it is mounted
        **Expected <div> components text to match (using ===), but it did not.**
        **Actual HTML: "Welcome to the react/typescript boilerplate 1"**
        **Expected HTML: "Welcome to the react/typescript boilerplate 2"**
        **Error: Expected <div> components text to match (using ===), but it did not.**
            **at <Jasmine>**
            **at checkCount (src/tests.ts:70104:35)**
            **at UserContext.<anonymous> (src/tests.ts:70124:9)**
            **at <Jasmine>**

Chrome 65.0.3325 (Windows 10 0.0.0) <App /> Should start counting once it is mounted FAILED
        **Expected <div> components text to match (using ===), but it did not.**
        **Actual HTML: "Welcome to the react/typescript boilerplate 1"**
        **Expected HTML: "Welcome to the react/typescript boilerplate 2"**
        **Error: Expected <div> components text to match (using ===), but it did not.**
            **at <Jasmine>**
            **at checkCount (src/tests.ts:70104:35)**
            **at UserContext.<anonymous> (src/tests.ts:70124:9)**
            **at <Jasmine>**
    √ Should render initially

Chrome 65.0.3325 (Windows 10 0.0.0): Executed 3 of 3 (1 FAILED) (0.116 secs / 0 secs)
TOTAL: 1 FAILED, 2 SUCCESS


1) Should start counting once it is mounted
     <App />
     **Expected <div> components text to match (using ===), but it did not.**
**Actual HTML: "Welcome to the react/typescript boilerplate 1"**
**Expected HTML: "Welcome to the react/typescript boilerplate 2"**
**Error: Expected <div> components text to match (using ===), but it did not.**
    **at <Jasmine>**
    **at checkCount (src/tests.ts:70104:35)**
    **at UserContext.<anonymous> (src/tests.ts:70124:9)**
    **at <Jasmine>**
